### ISSUE TITLE
Weights in example_geepack.R

### ISSUE THREAD

**Issue by jnkramer** [dalmiral/mHealthModeration#1]
Dear Prof Almirall,

thank you very much for uploading your code including the examples, this is incredibly helpful! I think I came across a minor issue in the example_geepack script.

Specifically, in line 74 

`d$pd <- ifelse(d$avail == 0, 0, ifelse(d$time > 3, fitpd$fitted.values, NA))`

the fitted values are of shorter length (9850) than the dataframe (10000) leading to possibly incorrect values in `d$pd`. Indeed, the first probability of `fitpd$fitted.values` is 0.323 (belonging to the fourth observation of the first participant) while the corresponding value in `d$pd` is 0.70. I think you would want to add NAs for `time < 4` directly to `fitpd$fitted.values` for the ifelse command to work correctly. Could you have a look at this?

Best,
Jan-Niklas Kramer

**Comment by aboruvka** [comment]
Thanks for raising this! It is indeed a bug, in both example files. I have run out of time to fix before I go on vacation, but will push some revisions when I get back. The solution you have proposed is correct.
